from pydantic import BaseModel

class Keypoint(BaseModel):
    x: float
    y: float
    z: float

class Frame(BaseModel):
    nose: Keypoint
    left_eye_inner: Keypoint
    left_eye: Keypoint
    left_eye_outer: Keypoint
    right_eye_inner: Keypoint
    right_eye: Keypoint
    right_eye_outer: Keypoint
    left_ear: Keypoint
    right_ear: Keypoint
    mouth_left: Keypoint
    mouth_right: Keypoint
    left_shoulder: Keypoint
    right_shoulder: Keypoint
    left_elbow: Keypoint
    right_elbow: Keypoint
    left_wrist: Keypoint
    right_wrist: Keypoint
    left_pinky: Keypoint
    right_pinky: Keypoint
    left_index: Keypoint
    right_index: Keypoint
    left_thumb: Keypoint
    right_thumb: Keypoint
    left_hip: Keypoint
    right_hip: Keypoint
    left_knee: Keypoint
    right_knee: Keypoint
    left_ankle: Keypoint
    right_ankle: Keypoint
    left_heel: Keypoint
    right_heel: Keypoint
    left_foot_index: Keypoint
    right_foot_index: Keypoint

    def to_dict(self):
        return {
            "nose": dict(self.nose),
            "left_eye_inner": dict(self.left_eye_inner),
            "left_eye": dict(self.left_eye),
            "left_eye_outer": dict(self.left_eye_outer),
            "right_eye_inner": dict(self.right_eye_inner),
            "right_eye": dict(self.right_eye),
            "right_eye_outer": dict(self.right_eye_outer),
            "left_ear": dict(self.left_ear),
            "right_ear": dict(self.right_ear),
            "mouth_left": dict(self.mouth_left),
            "mouth_right": dict(self.mouth_right),
            "left_shoulder": dict(self.left_shoulder),
            "right_shoulder": dict(self.right_shoulder),
            "left_elbow": dict(self.left_elbow),
            "right_elbow": dict(self.right_elbow),
            "left_wrist": dict(self.left_wrist),
            "right_wrist": dict(self.right_wrist),
            "left_pinky": dict(self.left_pinky),
            "right_pinky": dict(self.right_pinky),
            "left_index": dict(self.left_index),
            "right_index": dict(self.right_index),
            "left_thumb": dict(self.left_thumb),
            "right_thumb": dict(self.right_thumb),
            "left_hip": dict(self.left_hip),
            "right_hip": dict(self.right_hip),
            "left_knee": dict(self.left_knee),
            "right_knee": dict(self.right_knee),
            "left_ankle": dict(self.left_ankle),
            "right_ankle": dict(self.right_ankle),
            "left_heel": dict(self.left_heel),
            "right_heel": dict(self.right_heel),
            "left_foot_index": dict(self.left_foot_index),
            "right_foot_index": dict(self.right_foot_index),
        }

class Sign(BaseModel):
    sign_name: str
    video_url: str
    frame0: Frame
    frame1: Frame
    frame2: Frame
    frame3: Frame
    frame4: Frame
    frame5: Frame
    frame6: Frame
    frame7: Frame
    frame8: Frame
    frame9: Frame
    frame10: Frame
    frame11: Frame
    frame12: Frame
    frame13: Frame
    frame14: Frame
    frame15: Frame
    frame16: Frame
    frame17: Frame
    frame18: Frame
    frame19: Frame
    frame20: Frame
    frame21: Frame
    frame22: Frame
    frame23: Frame
    frame24: Frame
    frame25: Frame
    frame26: Frame
    frame27: Frame
    frame28: Frame
    frame29: Frame

    def to_dict(self):
        return {
            "sign_name": self.sign_name,
            "video_url": self.video_url,
            "frame0": self.frame0.to_dict(),
            "frame1": self.frame1.to_dict(),
            "frame2": self.frame2.to_dict(),
            "frame3": self.frame3.to_dict(),
            "frame4": self.frame4.to_dict(),
            "frame5": self.frame5.to_dict(),
            "frame6": self.frame6.to_dict(),
            "frame7": self.frame7.to_dict(),
            "frame8": self.frame8.to_dict(),
            "frame9": self.frame9.to_dict(),
            "frame10": self.frame10.to_dict(),
            "frame11": self.frame11.to_dict(),
            "frame12": self.frame12.to_dict(),
            "frame13": self.frame13.to_dict(),
            "frame14": self.frame14.to_dict(),
            "frame15": self.frame15.to_dict(),
            "frame16": self.frame16.to_dict(),
            "frame17": self.frame17.to_dict(),
            "frame18": self.frame18.to_dict(),
            "frame19": self.frame19.to_dict(),
            "frame20": self.frame20.to_dict(),
            "frame21": self.frame21.to_dict(),
            "frame22": self.frame22.to_dict(),
            "frame23": self.frame23.to_dict(),
            "frame24": self.frame24.to_dict(),
            "frame25": self.frame25.to_dict(),
            "frame26": self.frame26.to_dict(),
            "frame27": self.frame27.to_dict(),
            "frame28": self.frame28.to_dict(),
            "frame29": self.frame29.to_dict(),
        }
